/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <unistd.h>
#include "logicProcessorTable.h"
#include "proactiveMonitoring.h"

netsnmp_tdata_row *
logicProcessorTable_createEntry(netsnmp_tdata *table_data
                 , long  logicProcessorIndex
                );

/** Initializes the logicProcessorTable module */
void
init_logicProcessorTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_logicProcessorTable();
}


/** Initialize the logicProcessorTable table by defining its contents and how it's structured */
void
initialize_table_logicProcessorTable(void)
{
    const oid logicProcessorTable_oid[] = {1,3,6,1,4,1,8691,17,2,1,5};
    const size_t logicProcessorTable_oid_len   = OID_LENGTH(logicProcessorTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("logicProcessorTable:init", "initializing table logicProcessorTable\n"));

    reg = netsnmp_create_handler_registration(
              "logicProcessorTable",     logicProcessorTable_handler,
              logicProcessorTable_oid, logicProcessorTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_data = netsnmp_tdata_create_table( "logicProcessorTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for logicProcessorTable\n");
        return;
    }
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for logicProcessorTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: logicProcessorIndex */
                           0);

    table_info->min_column = COLUMN_LOGICPROCESSORINDEX;
    table_info->max_column = COLUMN_LOGICPROCESSORUSAGE;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    {
        int i;
        int v = sysconf(_SC_NPROCESSORS_ONLN);
        for (i=0; i<v; i++) {
            logicProcessorTable_createEntry(table_data, i+1);
        }
    }
}

    /* Typical data structure for a row entry */
struct logicProcessorTable_entry {
    /* Index values */
    long logicProcessorIndex;

    /* Column values */
//    long logicProcessorIndex;
    long logicProcessorUsage;

    int   valid;
};

/* create a new row in the table */
netsnmp_tdata_row *
logicProcessorTable_createEntry(netsnmp_tdata *table_data
                 , long  logicProcessorIndex
                ) {
    struct logicProcessorTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct logicProcessorTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

    //DEBUGMSGT(("logicProcessorTable:entry:create", "row 0x%x\n", (uintptr_t)row));
    entry->logicProcessorIndex = logicProcessorIndex;
    netsnmp_tdata_row_add_index( row, ASN_INTEGER,
                                 &(entry->logicProcessorIndex),
                                 sizeof(entry->logicProcessorIndex));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* remove a row from the table */
void
logicProcessorTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct logicProcessorTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

    //DEBUGMSGT(("logicProcessorTable:entry:remove", "row 0x%x\n", (uintptr_t)row));

    entry = (struct logicProcessorTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}


/** handles requests for the logicProcessorTable table */
int
logicProcessorTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct logicProcessorTable_entry          *table_entry;
    int                         ret;
    char cmd[BUF_SIZE];
    char result[BUF_SIZE];

    DEBUGMSGTL(("logicProcessorTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct logicProcessorTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_LOGICPROCESSORINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->logicProcessorIndex);
                break;
            case COLUMN_LOGICPROCESSORUSAGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                sprintf(cmd, "%s get_cpu_usage %ld", IMPL_FILE, table_entry->logicProcessorIndex-1);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->logicProcessorUsage = (long) (atof(result) + 0.5);
                } else {
                    return SNMP_ERR_NOERROR;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->logicProcessorUsage);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
