/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef LOGICPROCESSORTABLE_H
#define LOGICPROCESSORTABLE_H

/* function declarations */
void init_logicProcessorTable(void);
void initialize_table_logicProcessorTable(void);
Netsnmp_Node_Handler logicProcessorTable_handler;

/* column number definitions for table logicProcessorTable */
       #define COLUMN_LOGICPROCESSORINDEX		1
       #define COLUMN_LOGICPROCESSORUSAGE		2
#endif /* LOGICPROCESSORTABLE_H */
