/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef NETWORKSTATUSTABLE_H
#define NETWORKSTATUSTABLE_H

/* function declarations */
void init_networkStatusTable(void);
void initialize_table_networkStatusTable(void);
Netsnmp_Node_Handler networkStatusTable_handler;

/* column number definitions for table networkStatusTable */
       #define COLUMN_NETWORKADAPTERINDEX		1
       #define COLUMN_NETWORKFRIENDLYNAME		2
       #define COLUMN_CONNECTIONSTATUS		3
       #define COLUMN_LINKSPEED		4
       #define COLUMN_NETWORKUTILIZATION		5
#endif /* NETWORKSTATUSTABLE_H */
