/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "networkStatusTable.h"
#include "proactiveMonitoring.h"

    /* Typical data structure for a row entry */
struct networkStatusTable_entry {
    /* Index values */
    long networkAdapterIndex;

    /* Column values */
//    long networkAdapterIndex;
    char networkFriendlyName[128];
    size_t networkFriendlyName_len;
    long connectionStatus;
    long linkSpeed;
    long networkUtilization;

    int   valid;
};

netsnmp_tdata_row *
networkStatusTable_createEntry(netsnmp_tdata *table_data
                 , long  networkAdapterIndex
                );

/** Initializes the networkStatusTable module */
void
init_networkStatusTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_networkStatusTable();
}


/** Initialize the networkStatusTable table by defining its contents and how it's structured */
void
initialize_table_networkStatusTable(void)
{
    const oid networkStatusTable_oid[] = {1,3,6,1,4,1,8691,17,2,6,1};
    const size_t networkStatusTable_oid_len   = OID_LENGTH(networkStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("networkStatusTable:init", "initializing table networkStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "networkStatusTable",     networkStatusTable_handler,
              networkStatusTable_oid, networkStatusTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_data = netsnmp_tdata_create_table( "networkStatusTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for networkStatusTable\n");
        return;
    }
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for networkStatusTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: networkAdapterIndex */
                           0);

    table_info->min_column = COLUMN_NETWORKADAPTERINDEX;
    table_info->max_column = COLUMN_NETWORKUTILIZATION;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    {
        int i;
        int v;
        char cmd[BUF_SIZE];
        char result[BUF_SIZE];

        sprintf(cmd, "%s get_eth_count", IMPL_FILE);
        if (0 == exec_cmd(cmd, result)) {
            v = atoi(result);
            for (i=0; i<v; i++) {
                netsnmp_tdata_row *row;
                struct networkStatusTable_entry *entry;
                row = networkStatusTable_createEntry(table_data, i+1);
                entry = (struct networkStatusTable_entry *) row->data;
                sprintf(cmd, "%s get_eth_name %d", IMPL_FILE, i);
                if (0 == exec_cmd(cmd, result)) {
                    strcpy( entry->networkFriendlyName, result );
                    entry->networkFriendlyName_len = strlen(result);
                } else {
                    entry->networkFriendlyName[0] = '\0';
                    entry->networkFriendlyName_len = 0;
                }
            }
        }
    }
}

/* create a new row in the table */
netsnmp_tdata_row *
networkStatusTable_createEntry(netsnmp_tdata *table_data
                 , long  networkAdapterIndex
                ) {
    struct networkStatusTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct networkStatusTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

//    DEBUGMSGT(("networkStatusTable:entry:create", "row 0x%x\n", (uintptr_t)row));
    entry->networkAdapterIndex = networkAdapterIndex;
    netsnmp_tdata_row_add_index( row, ASN_INTEGER,
                                 &(entry->networkAdapterIndex),
                                 sizeof(entry->networkAdapterIndex));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* remove a row from the table */
void
networkStatusTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct networkStatusTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

//    DEBUGMSGT(("networkStatusTable:entry:remove", "row 0x%x\n", (uintptr_t)row));

    entry = (struct networkStatusTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}


/** handles requests for the networkStatusTable table */
int
networkStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct networkStatusTable_entry          *table_entry;
    int                         ret;
    char cmd[BUF_SIZE];
    char result[BUF_SIZE];

    DEBUGMSGTL(("networkStatusTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct networkStatusTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_NETWORKADAPTERINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->networkAdapterIndex);
                break;
            case COLUMN_NETWORKFRIENDLYNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->networkFriendlyName,
                                          table_entry->networkFriendlyName_len);
                break;
            case COLUMN_CONNECTIONSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                sprintf(cmd, "%s get_eth_link %ld", IMPL_FILE, table_entry->networkAdapterIndex-1);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->connectionStatus = (long) atoi(result);
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->connectionStatus);
                break;
            case COLUMN_LINKSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                sprintf(cmd, "%s get_eth_speed %ld", IMPL_FILE, table_entry->networkAdapterIndex-1);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->linkSpeed = (long) atoi(result);
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->linkSpeed);
                break;
            case COLUMN_NETWORKUTILIZATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                sprintf(cmd, "%s get_eth_usage %ld", IMPL_FILE, table_entry->networkAdapterIndex-1);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->networkUtilization = (long) atoi(result);
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->networkUtilization);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
