/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef PARTITIONSTATUSTABLE_H
#define PARTITIONSTATUSTABLE_H

/* function declarations */
void init_partitionStatusTable(void);
void initialize_table_partitionStatusTable(void);
Netsnmp_Node_Handler partitionStatusTable_handler;

/* column number definitions for table partitionStatusTable */
       #define COLUMN_PARTITIONSTATUSINDEX		1
       #define COLUMN_PARTITIONFRIENDLYNAME		2
       #define COLUMN_PARTITIONUSAGE		3
       #define COLUMN_PARTITIONTOTALSIZE		4
       #define COLUMN_PARTITIONAVAILABLESIZE		5
#endif /* PARTITIONSTATUSTABLE_H */
