/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "partitionStatusTable.h"
#include "proactiveMonitoring.h"

    /* Typical data structure for a row entry */
struct partitionStatusTable_entry {
    /* Index values */
    long partitionStatusIndex;

    /* Column values */
    //long partitionStatusIndex;
    char partitionFriendlyName[128];
    size_t partitionFriendlyName_len;
    long partitionUsage;
    long partitionTotalSize;
    long partitionAvailableSize;

    int   valid;
};

netsnmp_tdata_row *
partitionStatusTable_createEntry(netsnmp_tdata *table_data
                 , long  partitionStatusIndex
                );

/** Initializes the partitionStatusTable module */
void
init_partitionStatusTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_partitionStatusTable();
}


/** Initialize the partitionStatusTable table by defining its contents and how it's structured */
void
initialize_table_partitionStatusTable(void)
{
    const oid partitionStatusTable_oid[] = {1,3,6,1,4,1,8691,17,2,3,1};
    const size_t partitionStatusTable_oid_len   = OID_LENGTH(partitionStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("partitionStatusTable:init", "initializing table partitionStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "partitionStatusTable",     partitionStatusTable_handler,
              partitionStatusTable_oid, partitionStatusTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_data = netsnmp_tdata_create_table( "partitionStatusTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for partitionStatusTable\n");
        return;
    }
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for partitionStatusTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: partitionStatusIndex */
                           0);

    table_info->min_column = COLUMN_PARTITIONSTATUSINDEX;
    table_info->max_column = COLUMN_PARTITIONAVAILABLESIZE;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    {
        int i;
        int v;
        char cmd[BUF_SIZE];
        char result[BUF_SIZE];

        strcpy(cmd, "df | awk '{print $1}' |grep -vE 'tmpfs|rootfs|udev|Filesystem' | wc -l");
        if (0 == exec_cmd(cmd, result)) {
            v = atoi(result);
            for (i=0; i<v; i++) {
                netsnmp_tdata_row *row;
                struct partitionStatusTable_entry *entry;
                row = partitionStatusTable_createEntry(table_data, i+1);
                entry = (struct partitionStatusTable_entry *) row->data;
                sprintf(cmd, "printf $(df | awk '{print $1}' |grep -vE 'tmpfs|rootfs|udev|Filesystem' | head -n%d | tail -n1)", i + 1);
                if (0 == exec_cmd(cmd, result)) {
                    sprintf(entry->partitionFriendlyName, "%s", result);
                    entry->partitionFriendlyName_len = strlen(result);
                    entry->partitionUsage = 0;
                    entry->partitionTotalSize = 0;
                    entry->partitionAvailableSize = 0;
                }

            }
        }
    }
}

/* create a new row in the table */
netsnmp_tdata_row *
partitionStatusTable_createEntry(netsnmp_tdata *table_data
                 , long  partitionStatusIndex
                ) {
    struct partitionStatusTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct partitionStatusTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

    //DEBUGMSGT(("partitionStatusTable:entry:create", "row 0x%x\n", (uintptr_t)row));
    entry->partitionStatusIndex = partitionStatusIndex;
    netsnmp_tdata_row_add_index( row, ASN_INTEGER,
                                 &(entry->partitionStatusIndex),
                                 sizeof(entry->partitionStatusIndex));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* remove a row from the table */
void
partitionStatusTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct partitionStatusTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

    //DEBUGMSGT(("partitionStatusTable:entry:remove", "row 0x%x\n", (uintptr_t)row));

    entry = (struct partitionStatusTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}


/** handles requests for the partitionStatusTable table */
int
partitionStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct partitionStatusTable_entry          *table_entry;
    int                         ret;
    char cmd[BUF_SIZE];
    char result[BUF_SIZE];

    DEBUGMSGTL(("partitionStatusTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct partitionStatusTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_PARTITIONSTATUSINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->partitionStatusIndex);
                break;
            case COLUMN_PARTITIONFRIENDLYNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partitionFriendlyName,
                                          table_entry->partitionFriendlyName_len);
                break;
            case COLUMN_PARTITIONUSAGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }

                sprintf(cmd, "%s get_disk_usage %s", IMPL_FILE, table_entry->partitionFriendlyName);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->partitionUsage = (long) atof(result) + 0.5;
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->partitionUsage);
                break;
            case COLUMN_PARTITIONTOTALSIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                sprintf(cmd, "%s get_disk_total_size %s", IMPL_FILE, table_entry->partitionFriendlyName);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->partitionTotalSize = (long) atof(result);
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->partitionTotalSize);
                break;
            case COLUMN_PARTITIONAVAILABLESIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                sprintf(cmd, "%s get_disk_avail_size %s", IMPL_FILE, table_entry->partitionFriendlyName);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->partitionAvailableSize = (long) atof(result);
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->partitionAvailableSize);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
