/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PROACTIVEMONITORING_H
#define PROACTIVEMONITORING_H

#define BUF_SIZE        128
#define IMPL_FILE       "/usr/bin/mx_pro_mon_imp"
int exec_cmd(char *cmd, char *result);

/* function declarations */
void init_proactiveMonitoring(void);
Netsnmp_Node_Handler handle_cpuLogicCount;
Netsnmp_Node_Handler handle_cpuTotalUsage;
Netsnmp_Node_Handler handle_cpuTemperature;
Netsnmp_Node_Handler handle_cpuVoltage;
Netsnmp_Node_Handler handle_memoryUsage;
Netsnmp_Node_Handler handle_memoryTotalSize;
Netsnmp_Node_Handler handle_memoryAvailableSize;
Netsnmp_Node_Handler handle_dramVoltage;
Netsnmp_Node_Handler handle_mainboardPowerIndicator;
Netsnmp_Node_Handler handle_mainboardTemperature;
Netsnmp_Node_Handler handle_mainboardVoltage;

#endif /* PROACTIVEMONITORING_H */
