/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "serialPortStatusTable.h"
#include "proactiveMonitoring.h"

    /* Typical data structure for a row entry */
struct serialPortStatusTable_entry {
    /* Index values */
    long portStatusIndex;

    /* Column values */
//    long portStatusIndex;
    char serialPortFriendlyName[128];
    size_t serialPortFriendlyName_len;
    long portStatusValue;

    int   valid;
};

netsnmp_tdata_row *
serialPortStatusTable_createEntry(netsnmp_tdata *table_data
                 , long  portStatusIndex
                );

/** Initializes the serialPortStatusTable module */
void
init_serialPortStatusTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_serialPortStatusTable();
}


/** Initialize the serialPortStatusTable table by defining its contents and how it's structured */
void
initialize_table_serialPortStatusTable(void)
{
    const oid serialPortStatusTable_oid[] = {1,3,6,1,4,1,8691,17,2,5,1};
    const size_t serialPortStatusTable_oid_len   = OID_LENGTH(serialPortStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("serialPortStatusTable:init", "initializing table serialPortStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "serialPortStatusTable",     serialPortStatusTable_handler,
              serialPortStatusTable_oid, serialPortStatusTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_data = netsnmp_tdata_create_table( "serialPortStatusTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for serialPortStatusTable\n");
        return;
    }
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for serialPortStatusTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: portStatusIndex */
                           0);

    table_info->min_column = COLUMN_PORTSTATUSINDEX;
    table_info->max_column = COLUMN_PORTSTATUSVALUE;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    {
        int i;
        int v;
        char cmd[BUF_SIZE];
        char result[BUF_SIZE];

        sprintf(cmd, "%s get_uart_count", IMPL_FILE);
        if (0 == exec_cmd(cmd, result)) {
            v = atoi(result);
            for (i=0; i<v; i++) {
                netsnmp_tdata_row *row;
                struct serialPortStatusTable_entry *entry;
                row = serialPortStatusTable_createEntry(table_data, i+1);
                entry = (struct serialPortStatusTable_entry *) row->data;
                sprintf(cmd, "%s get_uart_name %d", IMPL_FILE, i);
                if (0 == exec_cmd(cmd, result)) {
                    strcpy( entry->serialPortFriendlyName, result );
                    entry->serialPortFriendlyName_len = strlen(result);
                } else {
                    entry->serialPortFriendlyName[0] = '\0';
                    entry->serialPortFriendlyName_len = 0;
                }
            }
        }
    }
}

/* create a new row in the table */
netsnmp_tdata_row *
serialPortStatusTable_createEntry(netsnmp_tdata *table_data
                 , long  portStatusIndex
                ) {
    struct serialPortStatusTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct serialPortStatusTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

//    DEBUGMSGT(("serialPortStatusTable:entry:create", "row 0x%x\n", (uintptr_t)row));
    entry->portStatusIndex = portStatusIndex;
    netsnmp_tdata_row_add_index( row, ASN_INTEGER,
                                 &(entry->portStatusIndex),
                                 sizeof(entry->portStatusIndex));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* remove a row from the table */
void
serialPortStatusTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct serialPortStatusTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

//    DEBUGMSGT(("serialPortStatusTable:entry:remove", "row 0x%x\n", (uintptr_t)row));

    entry = (struct serialPortStatusTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}


/** handles requests for the serialPortStatusTable table */
int
serialPortStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct serialPortStatusTable_entry          *table_entry;
    int                         ret;
    char cmd[BUF_SIZE];
    char result[BUF_SIZE];

    DEBUGMSGTL(("serialPortStatusTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct serialPortStatusTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTSTATUSINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portStatusIndex);
                break;
            case COLUMN_SERIALPORTFRIENDLYNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->serialPortFriendlyName,
                                          table_entry->serialPortFriendlyName_len);
                break;
            case COLUMN_PORTSTATUSVALUE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                sprintf(cmd, "%s get_uart_status %ld", IMPL_FILE, table_entry->portStatusIndex-1);
                if (0 == exec_cmd(cmd, result)) {
                    table_entry->portStatusValue = (long) atoi(result);
                } else {
                    continue;
                }

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portStatusValue);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
