/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SERIALPORTSTATUSTABLE_H
#define SERIALPORTSTATUSTABLE_H

/* function declarations */
void init_serialPortStatusTable(void);
void initialize_table_serialPortStatusTable(void);
Netsnmp_Node_Handler serialPortStatusTable_handler;

/* column number definitions for table serialPortStatusTable */
       #define COLUMN_PORTSTATUSINDEX		1
       #define COLUMN_SERIALPORTFRIENDLYNAME	2
       #define COLUMN_PORTSTATUSVALUE		3
#endif /* SERIALPORTSTATUSTABLE_H */
